version: '3.3'
services:
  mysql:
    image: 'mysql:5.7'
    environment:
      MYSQL_ROOT_PASSWORD: start_db
      MYSQL_USER: start_db
      MYSQL_PASSWORD: start_db
      MYSQL_DATABASE: meta_data
    ports:
      - '3306:3306'
  geomesa-hbase:
    image: spatiotemporallab/geomesa-hbase:latest
    hostname: geomesa-hbase-local
    ports:
      - '2181:2181'
      - '16010:16010'
      - '16000:16000'
      - '16020:16020'
      - '16030:16030'
